package handler

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"mmw-agent/internal/constants"
)

const websiteMarker = "# MMWX-WEBSITE v1"

type nginxWebsite struct {
	Domain    string `json:"domain"`
	Type      string `json:"type"`
	Value     string `json:"value,omitempty"`
	Path      string `json:"path"`
	ModTime   string `json:"mod_time,omitempty"`
	Size      int64  `json:"size"`
	Managed   bool   `json:"managed"`
	Legacy    bool   `json:"legacy"`
	Protected bool   `json:"protected"`
	Reason    string `json:"reason,omitempty"`
}

func nginxWebsiteDirs() []string {
	rt := inspectNginxRuntime()
	dirs := make([]string, 0, len(constants.NginxSSLServerDirPaths)+1)
	if rt.ManagedDir != "" {
		dirs = append(dirs, rt.ManagedDir)
	} else if rt.ConfigDir != "" {
		dirs = append(dirs, filepath.Join(rt.ConfigDir, "servers"))
	}
	dirs = append(dirs, constants.NginxSSLServerDirPaths...)
	seen := map[string]bool{}
	result := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		clean := filepath.Clean(dir)
		if !seen[clean] {
			seen[clean] = true
			result = append(result, clean)
		}
	}
	return result
}

var (
	websiteRootRE  = regexp.MustCompile(`(?m)^\s*root\s+([^;]+);`)
	websiteProxyRE = regexp.MustCompile(`(?m)^\s*proxy_pass\s+([^;]+);`)
	websiteNameRE  = regexp.MustCompile(`(?m)^\s*server_name\s+([^;]+);`)
	websiteLocRE   = regexp.MustCompile(`(?m)^\s*location\s+[^\s{]+\s*\{`)
	websiteSetRE   = regexp.MustCompile(`(?m)^\s*set\s+\$([A-Za-z_][A-Za-z0-9_]*)\s+([^;]+);`)
)

// resolveNginxWebsiteVariables expands variables declared by `set` in the same
// domain config. Website inventory is descriptive only, so unknown/built-in
// nginx variables are deliberately left untouched.
func resolveNginxWebsiteVariables(value, content string) string {
	variables := make(map[string]string)
	for _, match := range websiteSetRE.FindAllStringSubmatch(content, -1) {
		variables[match[1]] = strings.Trim(strings.TrimSpace(match[2]), `"'`)
	}
	for range len(variables) + 1 {
		previous := value
		for name, resolved := range variables {
			value = strings.ReplaceAll(value, "${"+name+"}", resolved)
			variableRE := regexp.MustCompile(`\$` + regexp.QuoteMeta(name) + `\b`)
			value = variableRE.ReplaceAllStringFunc(value, func(string) string { return resolved })
		}
		if value == previous {
			break
		}
	}
	return value
}

func classifyNginxWebsite(path string, info os.FileInfo, content string) nginxWebsite {
	domain := strings.ToLower(strings.TrimSuffix(filepath.Base(path), filepath.Ext(path)))
	if match := websiteNameRE.FindStringSubmatch(content); len(match) == 2 {
		if first := strings.Fields(match[1]); len(first) > 0 && first[0] != "_" {
			domain = strings.ToLower(first[0])
		}
	}
	entry := nginxWebsite{Domain: domain, Type: "unknown", Path: path, Size: info.Size(), ModTime: info.ModTime().UTC().Format(time.RFC3339)}
	entry.Managed = strings.Contains(content, websiteMarker)
	if match := regexp.MustCompile(`(?m)^# mmwx-site-type: (static|proxy)$`).FindStringSubmatch(content); len(match) == 2 {
		entry.Type = match[1]
	}
	if match := regexp.MustCompile(`(?m)^# mmwx-site-value-b64: ([A-Za-z0-9+/=]+)$`).FindStringSubmatch(content); len(match) == 2 {
		if decoded, err := base64.StdEncoding.DecodeString(match[1]); err == nil {
			entry.Value = string(decoded)
		}
	}
	if entry.Type == "unknown" {
		if match := websiteProxyRE.FindStringSubmatch(content); len(match) == 2 {
			entry.Type = "proxy"
			entry.Value = resolveNginxWebsiteVariables(strings.TrimSpace(match[1]), content)
		} else if match := websiteRootRE.FindStringSubmatch(content); len(match) == 2 {
			entry.Type, entry.Value = "static", strings.Trim(strings.TrimSpace(match[1]), `"'`)
		}
	}
	locations := websiteLocRE.FindAllString(content, -1)
	if len(locations) > 1 || strings.Contains(content, "grpc_pass ") || strings.Contains(content, "# MMWX-SYSTEM") {
		entry.Protected = true
		entry.Reason = "配置同时承载节点或系统入口"
	}
	// Recognize old standalone configs generated by MMWX. They remain removable
	// after a confirmation, while arbitrary user nginx files stay read-only.
	if !entry.Managed && !entry.Protected && entry.Type != "unknown" && len(locations) == 1 && strings.Contains(content, "127.0.0.1:8001") {
		entry.Managed, entry.Legacy = true, true
	}
	if !entry.Managed && entry.Reason == "" {
		entry.Reason = "外部或无法确认所有权的 Nginx 配置"
	}
	return entry
}

func scanNginxWebsites() ([]nginxWebsite, error) {
	seen := map[string]bool{}
	result := []nginxWebsite{}
	for _, dir := range nginxWebsiteDirs() {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, file := range entries {
			if file.IsDir() || !strings.HasSuffix(strings.ToLower(file.Name()), ".conf") {
				continue
			}
			path := filepath.Join(dir, file.Name())
			realPath, err := filepath.EvalSymlinks(path)
			if err != nil || !pathWithinDir(realPath, dir) {
				continue
			}
			info, err := os.Stat(realPath)
			if err != nil || info.Size() > 2<<20 {
				continue
			}
			data, err := os.ReadFile(realPath)
			if err != nil {
				continue
			}
			website := classifyNginxWebsite(realPath, info, string(data))
			if seen[website.Domain] {
				continue
			}
			seen[website.Domain] = true
			result = append(result, website)
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Domain < result[j].Domain })
	return result, nil
}

func pathWithinDir(path, dir string) bool {
	realDir, err := filepath.EvalSymlinks(dir)
	if err != nil {
		return false
	}
	rel, err := filepath.Rel(realDir, path)
	return err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(os.PathSeparator))
}

func portOwner(port int) string {
	hadTool := false
	for _, command := range [][]string{{"ss", "-ltnp"}, {"netstat", "-ltnp"}} {
		if _, err := exec.LookPath(command[0]); err != nil {
			continue
		}
		hadTool = true
		out, _ := exec.Command(command[0], command[1:]...).CombinedOutput()
		needle := fmt.Sprintf(":%d", port)
		for _, line := range strings.Split(string(out), "\n") {
			if strings.Contains(line, needle) {
				lower := strings.ToLower(line)
				switch {
				case strings.Contains(lower, "nginx"):
					return "nginx"
				case strings.Contains(lower, "xray") || strings.Contains(lower, "mmw-agent"):
					return "xray"
				default:
					return strings.TrimSpace(line)
				}
			}
		}
	}
	if !hadTool {
		return "unknown"
	}
	return ""
}

func (h *ManageHandler) HandleNginxWebsites(w http.ResponseWriter, r *http.Request) {
	if !h.authenticate(r) {
		writeError(w, http.StatusUnauthorized, "Unauthorized")
		return
	}
	switch r.Method {
	case http.MethodGet:
		websites, _ := scanNginxWebsites()
		runtime := inspectNginxRuntime()
		writeJSON(w, http.StatusOK, map[string]any{
			"success": true, "nginx": runtime, "websites": websites,
			"ports": map[string]string{"80": portOwner(80), "443": portOwner(443)},
		})
	case http.MethodDelete:
		h.deleteNginxWebsite(w, r)
	default:
		writeError(w, http.StatusMethodNotAllowed, "Method not allowed")
	}
}

func (h *ManageHandler) deleteNginxWebsite(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Domain string `json:"domain"`
	}
	if json.NewDecoder(r.Body).Decode(&req) != nil || strings.TrimSpace(req.Domain) == "" {
		writeError(w, http.StatusBadRequest, "domain required")
		return
	}
	domain := strings.ToLower(strings.TrimSpace(req.Domain))
	websites, _ := scanNginxWebsites()
	var target *nginxWebsite
	for i := range websites {
		if websites[i].Domain == domain {
			target = &websites[i]
			break
		}
	}
	if target == nil {
		writeError(w, http.StatusNotFound, "website not found")
		return
	}
	if !target.Managed || target.Protected {
		writeError(w, http.StatusConflict, "website config is external or protected")
		return
	}
	backup := target.Path + ".mmwx-delete-backup"
	_ = os.Remove(backup)
	if err := os.Rename(target.Path, backup); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	rollback := func(cause error) {
		_ = os.Rename(backup, target.Path)
		_ = nginxReload()
		writeError(w, http.StatusInternalServerError, cause.Error())
	}
	if err := nginxReload(); err != nil {
		rollback(err)
		return
	}
	if err := os.Remove(backup); err != nil {
		rollback(err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"success": true, "message": "website removed", "domain": domain})
}
